### ISSUE TITLE
How to add fabform.io to your theme ?

### ISSUE THREAD

**Issue by derrygeoff** [sharadcodes/hugo-theme-serial-programmer#2]
Hello

Is there anyway you can add https://fabform.io to your theme?

Geoff
https://fabform.io

**Comment by sharadcodes** [comment]
Yes, you can just add it on any page template or create your own template.

**Comment by sharadcodes** [comment]
Should I assume that you got your answer ? @derrygeoff

**Comment by sharadcodes** [comment]
I will close this issue now.
