### ISSUE TITLE
seems not work when I use this repo in theme

### ISSUE THREAD

**Issue by CollieIsCute** [sharadcodes/hugo-theme-serial-programmer#4]
This theme is great and I tried to use it in my theme directory. I can use `hugo server` command and this works perfect with `localhost:1313` . However, when I deploy this theme on github page, it's not working.

Here is my [website](https://collieiscute.github.io/), and this is my latest [broken github action](https://github.com/CollieIsCute/CollieIsCute.github.io/actions/runs/3212568923/jobs/5251550268), as well as my [github workflow yaml file](https://github.com/CollieIsCute/CollieIsCute.github.io/blob/main/.github/workflows/main.yml).   

Should I use this theme in `theme/` directory or simply fork this repo and modify it?

**Comment by CollieIsCute** [comment]
Fixed. my `config.toml` __baseURL__ need a '/' in the last.

after https://github.com/CollieIsCute/CollieIsCute.github.io/commit/37f24cf07e97657322865349570be119bf15ee85 , the issue is fixed.

**Comment by sharadcodes** [comment]
My apologies I was not online at the time you opened the issue.

**Comment by CollieIsCute** [comment]
Don't worry. Appreciate that!
